### ISSUE TITLE
Change Old GPSFix limit to 3

### ISSUE THREAD

**Issue by beroe** [mbari-org/auvstatus#79]
Currently at 4, pending incorporation of Carlos' fix for duplicates.

**Comment by beroe** [comment]
Code is at  #L1945

**Comment by carueda** [comment]
@beroe Not sure I follow, but, just in case, the new check for duplicates is in place in TethysDash since we had that discussion; it's just that the branch with such adjustments hasn't been merged into main. BTW, I may be doing that merge this week as all seems OK with GPSFix events, right?

**Comment by beroe** [comment]
Hi Carlos. Thanks, I wasn't clear if "merged into main" was when it would be live for the vehicles. I just noticed a pair of fixes that were  close together, so I thought I needed to switch it back to 4 events instead of just 3...
`
<img width="299" alt="image" src="https://github.com/mbari-org/auvstatus/assets/871533/6dfb74da-b018-49e9-9d2e-efd146777b57">
`

**Comment by beroe** [comment]
Thanks Carlos. Yes, there are two that are about a minute apart which was not useful for my dead-reckoning. I think I might have to change the approach, and look at the time difference from the most recent fix, before deciding which one to use. Normally it is not an issue, but when the vehicle sits on the surface for a while it throws off the average.
